### ISSUE TITLE
ci: Create workflow for automated releases

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/py-sdk#62]
### Example flow

```sh
poetry install
poetry run pytest 
```

### Bump the version

Using any bump rule with a valid semver string will change the version inside `pyproject.toml`. For example, 

```
poetry version patch # moves from x.y.14 to x.y.15
poetry version minor # moves from x.5.z to x.6.0
poetry version major # moves from 3.y.z to 4.0.0
```
The list of bump rules includes:
patch, minor, major, prepatch, preminor, premajor, prerelease. 

#### We can also set conditional logic to control this with the commit title.

```yaml
# Rough outline to get someone started
job_name:
  runs-on: ubuntu-20.04
  if: "!contains(github.event.head_commit.message, 'SKIP BUMP')"    <--- skips everything in this job if head commit message does not contain 'SKIP BUMP'

  steps:
    - uses: ....
    - name: condition 1
      if: "contains(github.event.head_commit.message, 'CONDITION 1 MSG')"
      run: command(s) for condition 1

   - name: not condition 2
      if: "!contains(github.event.head_commit.message, 'CONDITION 2 MSG')"
      run: command(s) for condition 2
  # ...
```

- [x] Add a version bumping step to the GHA workflow

### Build and Publish

- [x] Set PYPI credentials in the repo or organization secrets.

```sh
poetry build 
poetry publish --username $PYPI_USER --password $PYPI_TOKEN
```
